apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "calibre-web.fullname" . }}
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "calibre-web.fullname" . }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "calibre-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calibre-web.selectorLabels" . | nindent 8 }}
      {{- if .Values.extraEnv }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "calibre-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.extraEnv }}
          envFrom:
            - configMapRef:
                name: {{ include "calibre-web.fullname" . }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 100
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 300
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /books
              name: data
            - mountPath: /config
              name: config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
    {{- if or (or (not .Values.persistence.data.enabled) (and .Values.persistence.data.enabled .Values.persistence.data.existingClaim)) (or (not .Values.persistence.config.enabled) (and .Values.persistence.config.enabled .Values.persistence.config.existingClaim)) }}
      volumes:
        {{- if and .Values.persistence.data.enabled .Values.persistence.data.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim }}
        {{- else if not .Values.persistence.data.enabled }}
          emptyDir: {}
        {{- end }}
        {{- if and .Values.persistence.config.enabled .Values.persistence.config.existingClaim }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim }}
        {{- else if not .Values.persistence.config.enabled }}
          emptyDir: {}
        {{- end }}
    {{- end }}
{{- if or (and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim)) (and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim)) }}
  volumeClaimTemplates:
  {{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
    - metadata:
        name: data
      {{- with .Values.persistence.data.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.data.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.data.size | quote }}
      {{- if .Values.persistence.data.storageClass }}
      {{- if (eq "-" .Values.persistence.data.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.data.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
  {{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
    - metadata:
        name: config
      {{- with .Values.persistence.config.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.config.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.config.size | quote }}
      {{- if .Values.persistence.config.storageClass }}
      {{- if (eq "-" .Values.persistence.config.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.config.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
