{{- if .Values.extraEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
data:
{{- with .Values.extraEnv }}
{{ tpl (toYaml .) $ | indent 2 }}
{{- end }}
{{- end }}
