{{- if .Values.service.udp }}
{{- if .Values.service.udp.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}-lb-udp
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.service.udp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.udp.type }}
  ports:
    {{- range .Values.service.udp.ports }}
    - name: jellyfin-{{ .port }}
      port: {{ .port }}
      targetPort: {{ .containerPort }}
      protocol: UDP
    {{- end }}
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
