apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.main.type }}
  ports:
    - port: {{ .Values.service.main.port }}
      targetPort: 8096
      protocol: TCP
      name: http
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
