{{- if .Values.extraEnvSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim.fullname" . }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
stringData:
{{- with .Values.extraEnvSecret }}
{{ tpl (toYaml .) $ | indent 2 }}
{{- end }}
{{- end }}
