---
{{- if and .Values.service.tcp .Values.service.tcp.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}-lb-tcp
  labels:
    {{- include "plex.labels" . | nindent 4 }}
  {{- with .Values.service.tcp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.tcp.type }}
  ports:
  {{- range .Values.service.tcp.ports }}
    - name: plex-{{ .port }}
      port: {{ .port }}
      targetPort: {{ .containerPort }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
{{- end }}
