{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teamspeak.serviceAccountName" . }}
  labels:
{{ include "teamspeak.labels" . | nindent 4 }}
{{- end -}}
