apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8211
      name: "8211"
      protocol: UDP
  selector:
    {{- include "palworld.selectorLabels" . | nindent 4 }}
