apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
data:
  settings.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
