{{- if and (eq .Values.rootDir.type "pvc") (not .Values.rootDir.pvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-rootdir
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.rootDir.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.rootDir.pvc.size | quote }}
  {{- if .Values.rootDir.pvc.storageClassName }}
  storageClassName: {{ .Values.rootDir.pvc.storageClassName }}
  {{- end }}
{{- end }}
