{{- if and .Values.db.pvc.enabled (not .Values.db.pvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-db
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.db.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.pvc.size | quote }}
  {{- if .Values.db.pvc.storageClassName }}
  storageClassName: {{ .Values.db.pvc.storageClassName }}
  {{- end }}
{{- end }}
