{{- if .Values.rtorrentConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rtorrent-vpn.fullname" . }}-rtorrent-rc
  labels:
    {{- include "rtorrent-vpn.labels" . | nindent 4 }}
data:
{{- with .Values.rtorrentConfig }}
{{ tpl (toYaml .) $ | indent 2 }}
{{- end }}
{{- end }}
