{{- if .Values.customScriptsConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.customScriptsConfigMap.name }}
  labels:
  {{- include "rtorrent-vpn.labels" . | nindent 4 }}
data:
{{- with .Values.customScriptsConfigMap.data }}
{{ tpl (toYaml .) $ | indent 2 }}
{{- end }}
{{- end }}
