{{- if .Values.extraEnvSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rtorrent-vpn.fullname" . }}
  labels:
    {{- include "rtorrent-vpn.labels" . | nindent 4 }}
data:
{{- range $index, $element :=  .Values.extraEnvSecret }}
{{ $index | indent 2 }}: {{ $element | b64enc | quote }}
{{- end }}
{{- end }}
