{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rtorrent-vpn.serviceAccountName" . }}
  labels:
{{ include "rtorrent-vpn.labels" . | nindent 4 }}
{{- end -}}
