apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtorrent-vpn.fullname" . }}
  labels:
    {{- include "rtorrent-vpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rtorrent-vpn.selectorLabels" . | nindent 4 }}
---
{{- if .Values.privoxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtorrent-vpn.fullname" . }}-privoxy
  labels:
    {{- include "rtorrent-vpn.labels" . | nindent 4 }}
  {{- with .Values.privoxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.privoxy.service.type }}
  ports:
    - port: {{ .Values.privoxy.service.port }}
      targetPort: privoxy
      protocol: TCP
      name: privoxy
  selector:
    {{- include "rtorrent-vpn.selectorLabels" . | nindent 4 }}
{{- end }}
