apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rtorrent-vpn.fullname" . }}
  labels:
    {{- include "rtorrent-vpn.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rtorrent-vpn.fullname" . }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "rtorrent-vpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rtorrent-vpn.selectorLabels" . | nindent 8 }}
      {{- if or .Values.extraEnvSecret (or .Values.extraEnvConfigMap (or .Values.customScriptsConfigMap (or .Values.rtorrentConfig .Values.ovpnConfig))) }}
      annotations:
        {{- if or .Values.extraEnvConfigMap (or .Values.customScriptsConfigMap .Values.rtorrentConfig) }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if or .Values.extraEnvSecret .Values.ovpnConfig }}
        checksum/secret: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rtorrent-vpn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if or .Values.rtorrentConfig .Values.ovpnConfig }}
      initContainers:
        - name: init-ops
          image: "{{ .Values.initContainerImage.repository }}:{{ .Values.initContainerImage.tag }}"
          imagePullPolicy: {{ .Values.initContainerImage.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |-
              echo "Copying files" \
              {{- if .Values.rtorrentConfig }}
              && cp /tmp/rtorrent/rtorrent.rc /config/rtorrent/config/rtorrent.rc \
              {{- end }}
              {{- if .Values.ovpnConfig }}
              && cp -LR /tmp/openvpn/* /config/openvpn/ \
              {{- end }}
              && echo "Copying done."
          volumeMounts:
            {{- if .Values.rtorrentConfig }}
            - mountPath: /tmp/rtorrent/rtorrent.rc
              name: rtorrent-config-temp
              subPath: rtorrent.rc
            - mountPath: /config/rtorrent/config
              name: rtorrent-config
            {{- end }}
            {{- if .Values.ovpnConfig }}
            - mountPath: /tmp/openvpn
              name: openvpn-config-temp
            - mountPath: /config/openvpn
              name: openvpn-config
            {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.ovpnConfig }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.extraEnvConfigMap .Values.extraEnvSecret }}
          envFrom:
            {{- if .Values.extraEnvConfigMap}}
            - configMapRef:
                name: {{ include "rtorrent-vpn.fullname" . }}
            {{- end }}
            {{- if .Values.extraEnvSecret}}
            - secretRef:
                name: {{ include "rtorrent-vpn.fullname" . }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 9080
          {{- if .Values.privoxy.enabled }}
            - name: privoxy
              containerPort: 8118
          {{- end }}
          readinessProbe:
            exec:
              command:
                - pgrep
                - rtorrent
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 90
          livenessProbe:
            exec:
              command:
                - pgrep
                - rtorrent
            initialDelaySeconds: 1000
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
            {{- if .Values.rtorrentConfig }}
            - mountPath: /config/rtorrent/config
              name: rtorrent-config
            {{- end }}
            {{- if .Values.ovpnConfig }}
            - mountPath: /config/openvpn
              name: openvpn-config
            {{- end }}
          {{- if .Values.customVolumeMounts }}
{{ tpl .Values.customVolumeMounts . | indent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
    {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- if .Values.customVolumes }}
{{ tpl .Values.customVolumes . | indent 8 }}
        {{- end }}
        {{- if .Values.rtorrentConfig }}
        - name: rtorrent-config
          emptyDir: {}
        - name: rtorrent-config-temp
          configMap:
            name: {{ include "rtorrent-vpn.fullname" . }}-rtorrent-rc
            items:
              - key: rtorrent.rc
                path: rtorrent.rc
        {{- end }}
        {{- if .Values.ovpnConfig }}
        - name: openvpn-config
          emptyDir: {}
        - name: openvpn-config-temp
          secret:
            secretName: {{ include "rtorrent-vpn.fullname" . }}-ovpn
        - name: dev-net-tun
          hostPath:
            type: CharDevice
            path: /dev/net/tun
        {{- end }}
        - name: data
        {{- if and .Values.persistence.data.enabled .Values.persistence.data.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim }}
        {{- else if not .Values.persistence.data.enabled }}
          emptyDir: {}
        {{- end }}
        - name: config
        {{- if and .Values.persistence.config.enabled .Values.persistence.config.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim }}
        {{- else if not .Values.persistence.config.enabled }}
          emptyDir: {}
        {{- end }}
{{- if or (and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim)) (and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim)) }}
  volumeClaimTemplates:
  {{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
    - metadata:
        name: data
      {{- with .Values.persistence.data.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.data.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.data.size | quote }}
      {{- if .Values.persistence.data.storageClass }}
      {{- if (eq "-" .Values.persistence.data.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.data.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
  {{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
    - metadata:
        name: config
      {{- with .Values.persistence.config.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.config.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.config.size | quote }}
      {{- if .Values.persistence.config.storageClass }}
      {{- if (eq "-" .Values.persistence.config.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.config.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
