apiVersion: v2
name: filebrowser
description: A Helm chart for the File Browser project
type: application
version: 0.1.0
appVersion: v2.22.4
home: https://filebrowser.org
keywords:
  - filebrowser
  - file-browser
  - file-server
  - http-file-server
sources:
  - https://github.com/filebrowser/filebrowser
  - https://github.com/oguzkilcan/helm-charts
icon: https://raw.githubusercontent.com/filebrowser/logo/master/icon.svg
maintainers:
  - name: oguzkilcan
